//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_Data.BT_EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class bt_CollegeBranches
    {
        public System.Guid BranchId { get; set; }
        public string Name { get; set; }
        public System.Guid CollegeId { get; set; }
    
        public virtual bt_College bt_College { get; set; }
    }
}
