//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_Data.BT_EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BestTravelingEntities : DbContext
    {
        public BestTravelingEntities()
            : base("name=BestTravelingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bt_CollegeBranches> bt_CollegeBranches { get; set; }
        public virtual DbSet<bt_State> bt_State { get; set; }
        public virtual DbSet<bt_Roles2> bt_Roles2 { get; set; }
        public virtual DbSet<bt_Country> bt_Country { get; set; }
        public virtual DbSet<bt_Roles> bt_Roles { get; set; }
        public virtual DbSet<bt_City> bt_City { get; set; }
        public virtual DbSet<bt_District> bt_District { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<bt_Office> bt_Office { get; set; }
        public virtual DbSet<bt_Address> bt_Address { get; set; }
        public virtual DbSet<bt_Designation> bt_Designation { get; set; }
        public virtual DbSet<bt_OfficeOperator> bt_OfficeOperator { get; set; }
        public virtual DbSet<bt_Gender> bt_Gender { get; set; }
        public virtual DbSet<bt_User> bt_User { get; set; }
        public virtual DbSet<bt_Fares> bt_Fares { get; set; }
        public virtual DbSet<bt_College> bt_College { get; set; }
        public virtual DbSet<bt_CollegeDirector> bt_CollegeDirector { get; set; }
    
        public virtual int usp_AddOffice(string officeAddressXml, string officeDetailXml)
        {
            var officeAddressXmlParameter = officeAddressXml != null ?
                new ObjectParameter("OfficeAddressXml", officeAddressXml) :
                new ObjectParameter("OfficeAddressXml", typeof(string));
    
            var officeDetailXmlParameter = officeDetailXml != null ?
                new ObjectParameter("OfficeDetailXml", officeDetailXml) :
                new ObjectParameter("OfficeDetailXml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AddOffice", officeAddressXmlParameter, officeDetailXmlParameter);
        }
    
        public virtual int usp_UpdateOffice(string officeAddressXml, string officeDetailXml)
        {
            var officeAddressXmlParameter = officeAddressXml != null ?
                new ObjectParameter("OfficeAddressXml", officeAddressXml) :
                new ObjectParameter("OfficeAddressXml", typeof(string));
    
            var officeDetailXmlParameter = officeDetailXml != null ?
                new ObjectParameter("OfficeDetailXml", officeDetailXml) :
                new ObjectParameter("OfficeDetailXml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateOffice", officeAddressXmlParameter, officeDetailXmlParameter);
        }
    
        public virtual int usp_AddOperator(string operatorDetailXml, string operatorAddressXml)
        {
            var operatorDetailXmlParameter = operatorDetailXml != null ?
                new ObjectParameter("OperatorDetailXml", operatorDetailXml) :
                new ObjectParameter("OperatorDetailXml", typeof(string));
    
            var operatorAddressXmlParameter = operatorAddressXml != null ?
                new ObjectParameter("OperatorAddressXml", operatorAddressXml) :
                new ObjectParameter("OperatorAddressXml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AddOperator", operatorDetailXmlParameter, operatorAddressXmlParameter);
        }
    }
}
