//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestTraveling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bt_College
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bt_College()
        {
            this.bt_CollegeBranches = new HashSet<bt_CollegeBranches>();
        }
    
        public System.Guid CollegeId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<System.Guid> DistrictId { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public string DirecotrName { get; set; }
        public string Code { get; set; }
    
        public virtual bt_City bt_City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bt_CollegeBranches> bt_CollegeBranches { get; set; }
        public virtual bt_District bt_District { get; set; }
    }
}
