//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestTraveling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bt_District
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bt_District()
        {
            this.bt_City = new HashSet<bt_City>();
            this.bt_College = new HashSet<bt_College>();
        }
    
        public System.Guid DistrictId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> StateId { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bt_City> bt_City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bt_College> bt_College { get; set; }
        public virtual bt_State bt_State { get; set; }
        public virtual bt_CollegeDirector bt_CollegeDirector { get; set; }
    }
}
